
set(CTEST_PROJECT_NAME "VecGeom")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

set(CTEST_SOURCE_DIRECTORY "$ENV{CMAKE_SOURCE_DIR}")  
set(CTEST_BINARY_DIRECTORY "$ENV{CMAKE_BINARY_DIR}")
set(CTEST_COMMAND "ctest")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.cern.ch")
set(CTEST_DROP_LOCATION "/submit.php?project=VecGeom")
set(CTEST_DROP_SITE_CDASH TRUE)

