#! /usr/bin/env python

'''
EXPERIMENTAL: this is a demonstrator and not the final product!
Tested with ROOT
'''

import sys
import common

SA_CLANG_C = "/usr/bin/clang" #note: this is system specific

if __name__ == "__main__":
   command = sys.argv
   command[0] = SA_CLANG_C #avoid infinite recursion
   retCode = common.Analyze(command,SA_CLANG_C)
   sys.exit(retCode)
